# Generated by Django 4.2.4 on 2023-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='grade',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
